version: '3.8'

services:
  # Service d'entraînement
  train:
    build:
      context: .
      dockerfile: train/Dockerfile
    container_name: cnn_training
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - ml_network

  # Service API de prédiction avec interface graphique
  api:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: cnn_api
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models           # Pour charger le modèle
      - ./app/templates:/app/templates # Pour l'interface (live reload)
      - ./data:/app/data               # Si besoin des données
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
    networks:
      - ml_network
    restart: unless-stopped
    depends_on:
      - train

networks:
  ml_network:
    driver: bridge